### ISSUE TITLE
PV problem

### ISSUE THREAD

**Issue by LocutusOfPenguin** [niklasf/python-chess#40]
Hello,
im not sure, if its a python-chess problem, or a picochess one.

I played the following game. On move 19, stockfish wanted to play Nd6-e4, but i played Nf6-e4
At this time: program in pondering mode. Then the program crushed with error message.
Could that be a problem with both N can go to e4?

GAME:
1. d4 d5 2. Bf4 c5 3. c3 Nc6 4. Nf3 Nf6 5. e3 Bg4 6. Be2 e6 7. O-O cxd4 8. cxd4
Bd6 9. Bxd6 Qxd6 10. Nc3 O-O 11. h3 Bxf3 12. Bxf3 Rfc8 13. Rc1 h6 14. Re1 Ne7
15. Qb3 Qd7 16. Be2 Nf5 17. Bb5 Qd8 18. Bd3 Nd6 19. Nb5 Nfe4 20. Nxd6 Nxd6 21.
Qa3 1-0

ErrorLog:
2015-07-20 07:27:41.531 DEBUG picochess - main: User move [c3b5]
2015-07-20 07:27:41.589 INFO dgtdisplay - run: Search already stopped
2015-07-20 07:27:41.661 INFO dgtdisplay - run: Search ponder started
2015-07-20 07:27:41.691 ERROR uci - _info: exception parsing pv
Traceback (most recent call last):
  File "./libs/chess/uci.py", line 724, in _info
    pv.append(board.push_uci(token))
  File "./libs/chess/__init__.py", line 2361, in push_uci
    move = self.parse_uci(uci)
  File "./libs/chess/__init__.py", line 2348, in parse_uci
    raise ValueError("illegal uci: {0}".format(repr(uci)))
ValueError: illegal uci: 'd6e4'

**Comment by niklasf** [comment]
Hi. UCI notation like d6e4 is not really ambiguous, so I can't imagine it has anything to do with that. Maybe the move is parsed in the context of a wrong position. I added some extra info to the exception. Can you please try again with those changes included?

**Comment by LocutusOfPenguin** [comment]
ok, you are right. Prob. nothing to do with "ambiguous". Your extended error message, already HELP!
after 18.Nd6 i get:
illegal uci: 'a2a3' in r1rq2k1/pp3pp1/3npn1p/3p4/3P4/Q1NBP2P/PP3PP1/2R1R1K1 b - - 11 19
illegal uci: 'b3b5' in r2q2k1/pp3pp1/2r1pn1p/1n1p4/3P4/Q2BP2P/PP3PP1/2R1R1K1 w - - 0 21
illegal uci: 'c6b6' in r2q2k1/pp3pp1/2r1pn1p/1n1p4/3P4/Q2BP2P/PP3PP1/2R1R1K1 w - - 0 21

Doesn't look too good for me ;-) Digging-mode

**Comment by niklasf** [comment]
The full debug log of the engine communication might also be intresting.

This can not be picochess' fault (alone). The internal board should always match what the engine is calculating.

**Comment by niklasf** [comment]
Does the output from stockfish contain any `refutation`s or `currline`s? I think I might be incorrectly mixing them together.

**Comment by LocutusOfPenguin** [comment]
Sending this 3 commands , doesn't show an error.
I'm still trying to limit the setup to provoke an error:

setup:r1rq2k1/pp3pp1/4pn1p/3p1n2/3P4/1QNBP2P/PP3PP1/2R1R1K1 b - - 0 1
button:3
f5d6

playing the whole game, always gets this error ...but thats not very enjoyful ;-)

**Comment by niklasf** [comment]
The virtual dgt board is awesome for debugging and testing! Well done!

I do not get an error message when trying out your master branch. Should I do something different?

```
niklas@niklas-xmg:~/Projekte/picochess$ stockfish 
Stockfish 230814 64 by Tord Romstad, Marco Costalba and Joona Kiiski
quit
niklas@niklas-xmg:~/Projekte/picochess$ git rev-parse --short HEAD
b35e5fc
niklas@niklas-xmg:~/Projekte/picochess$ ./picochess.py 
2015-07-21 14:41:46.172 WARNING picochess - main: No DGT board port provided
PicoChess v047:>setup:r1r3k1/pp1q1pp1/4pn1p/1B1p1n2/3P4/1QN1P2P/PP3PP1/2R1R1K1 b - - 0 1
PicoChess v047:>Why we stop an already stopped engine??
clock not ready
DGT clock txt:newgam
button:3
PicoChess v047:>clock not ready
DGT clock txt:analyse
Computer starts pondering
DGT clock mov:d7e7
DGT clock mov:d7e7
DGT clock mov:d7e7
DGT clock mov:d7e7
DGT clock mov:d7e7
DGT clock mov:d7e7
DGT clock mov:d7e7
DGT clock mov:d7e7
DGT clock mov:d7e7
DGT clock mov:d7e7
DGT clock mov:d7e7
DGT clock mov:d7e7
DGT clock mov:d7e7
DGT clock mov:d7e7
DGT clock mov:d7e7
DGT clock mov:d7d8
DGT clock mov:d7d8
DGT clock mov:d7d8
DGT clock mov:d7d8
DGT clock mov:d7d8
DGT clock mov:d7d8
DGT clock mov:d7d8
d7d8
PicoChess v047:>Computer stops pondering
DGT clock txt:ok mode
Computer starts pondering
DGT clock mov:d7d8
DGT clock mov:d7d8
DGT clock mov:b5d3
DGT clock mov:b5d3
DGT clock mov:b5d3
DGT clock mov:b5d3
DGT clock mov:b5d3
DGT clock mov:b5d3
DGT clock mov:b5d3
DGT clock mov:b5d3
DGT clock mov:b5d3
DGT clock mov:b5d3
DGT clock mov:b5d3
DGT clock mov:b5d3
DGT clock mov:b5d3
DGT clock mov:b5d3
DGT clock mov:b5d3
DGT clock mov:b5d3
DGT clock mov:b5d3
DGT clock mov:b5d3
DGT clock mov:b5d3
DGT clock mov:b5d3
DGT clock mov:b5d3
DGT clock mov:b5d3
DGT clock mov:b5d3
DGT clock mov:b5d3
```

**Comment by niklasf** [comment]
Can you try to explain what the issue was? There might also be something that should be fixed in python-chess.

**Comment by LocutusOfPenguin** [comment]
not now, at least not here (sorry!) but irc/skype is ok - or wait for my talk to shiv first (but he is often busy) .. I'm still not sure i really solved it.

**Comment by niklasf** [comment]
Looking at your latest commit reminded me of making a copy for the internal board. I double checked and - alas - I lost that in the rewrite. This would explain all kinds of wierd effects when using the board concurrently.

**Comment by LocutusOfPenguin** [comment]
Its ok.
I have to say "MANY THANKS" for this rewrite. It not only allows me to stop searching (on button press), also helps solving some issues when the user is sliding pieces, takebacks, and so on.

**Comment by niklasf** [comment]
Thanks. So I am assuming this was the issue.

**Comment by LocutusOfPenguin** [comment]
Yes.
Today or tomorrow, i gonna release the new version with "stop search".
If y want, y can take a look at uci.py (only) - at my branch - to see what i did with all this python-chess - maybe get an idea for improvement (you or me).

**Comment by jackalsh** [comment]
I have the same issue, exectly same error.
In my case, I wrote script for scanning database of positions while looking for mates. When running in PyCharm, never got to reproduce the error to catch it with debugger, but while running in several processes it always happen in random times on random positions.
